language: scala

scala:
  - 2.13.2

jdk:
  - oraclejdk11

script:
  - sbt +test "examples/runMain xs4s.example.FindMostPopularWikipediaKeywordsFs2App" "examples/runMain xs4s.example.FindMostPopularWikipediaKeywordsPlainScalaApp" 

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
